services:
    victoire_core.widget_sharethis_content_resolver:
        class: Victoire\Widget\ShareThisBundle\Resolver\WidgetShareThisResolver
        arguments:
            - "%victoire_sharethis.shareThisPubKey%"
        parent: victoire_widget.base_widget_content_resolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: ShareThis }

    victoire.widget.sharethis:
        class: Victoire\Widget\ShareThisBundle\Entity\WidgetShareThis

    #alias to the form
    victoire.widget.form.sharethis:
        class: Victoire\Widget\ShareThisBundle\Form\WidgetShareThisType
        tags:
            - { name: form.type }
